image: jakzal/phpqa:latest

before_script:
  - composer install --prefer-dist --no-interaction

cache:
  paths:
    - vendor/

stages:
  - CodeStandards
  - UnitTests

phpcs:
  stage: CodeStandards
  script:
    - phpcs --standard=PSR12 --ignore=vendor/ app/Http/Controllers
  allow_failure: false

# larastan:
#  stage: CodeStandards
#  script:
#    - phpstan analyse app/Http/Controllers --level=max
#  allow_failure: true

phpunit:
  stage: UnitTests
  script:
    - phpunit --configuration phpunit.xml --filter testThatTrueIsTrue
  allow_failure: false