image: jakzal/phpqa:latest

before_script:
  - composer install --prefer-dist --no-interaction

cache:
  paths:
    - vendor/

stages:
  - CodeStandards
  - UnitTests

phpcs:
  stage: CodeStandards
  script:
    - phpcs --standard=PSR12 --ignore=vendor/ ./src
  allow_failure: false

phpstan:
  stage: CodeStandards
  script:
    - phpstan analyse ./src --level=max
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
    - phpunit --configuration phpunit.xml
  allow_failure: false